<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-05T12:09:06 IST" name="Default suite" finished-at="2024-09-05T12:14:06 IST" duration-ms="300453">
    <groups>
    </groups>
    <test started-at="2024-09-05T12:09:06 IST" name="Default test" finished-at="2024-09-05T12:14:06 IST" duration-ms="300453">
      <class name="testcases.TC01_Pairing_BlewithRouter">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:08:55 IST" name="beforeSuite" finished-at="2024-09-05T12:09:06 IST" duration-ms="10081" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:09:06 IST" name="beforeTest" finished-at="2024-09-05T12:09:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:09:06 IST" name="startTestCase" finished-at="2024-09-05T12:09:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:09:06 IST" name="beforeMethod" finished-at="2024-09-05T12:09:06 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:09:06 IST" name="removerepair" finished-at="2024-09-05T12:14:06 IST" duration-ms="299859" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:140)
at pages.HomePage.clickONOFFButton(HomePage.java:23)
at testcases.TC01_Pairing_BlewithRouter.pairBlewithoutRouter(TC01_Pairing_BlewithRouter.java:76)
at testcases.TC01_Pairing_BlewithRouter.removerepair(TC01_Pairing_BlewithRouter.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:14:06 IST" name="afterMethod" finished-at="2024-09-05T12:14:06 IST" duration-ms="463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:14:06 IST" name="afterTest" finished-at="2024-09-05T12:14:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:testcases.TC01_Pairing_BlewithRouter@3ad83a66]" started-at="2024-09-05T12:14:06 IST" name="afterSuite" finished-at="2024-09-05T12:14:06 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC01_Pairing_BlewithRouter -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
